//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nomina
    {
        public int IDEmpleado { get; set; }
        public int IDNomina { get; set; }
        public decimal Monto { get; set; }
        public string NombreUsuario { get; set; }
        public System.DateTime FechaPago { get; set; }
        public int IDConcepto { get; set; }
    
        public virtual Conceptos Conceptos { get; set; }
        public virtual Empleados Empleados { get; set; }
    }
}
